In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score
from sklearn.metrics import confusion_matrix

In [2]:
X,y=make_classification(n_samples=1000,n_features=5,random_state=123)

In [3]:
print(X)

[[ 0.87728113 -0.59642825  0.44019839 -0.52108094  0.31432298]
 [ 0.55856502 -0.41451292  0.813623   -0.54325372  0.14734302]
 [-0.90289911  0.38303337 -0.71157267 -0.86768895 -0.67394137]
 ...
 [ 1.7713853  -0.96445461  0.99337636  0.40674576  0.99881985]
 [-1.19977749  0.48167954  1.47831033 -1.31903526 -0.93698258]
 [ 0.33976266 -0.29183452 -0.82476815 -0.57191024  0.02935597]]


In [4]:
print(y)

[0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 0 1 1
 0 1 1 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0
 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 1
 1 0 1 1 0 0 1 1 1 0 0 1 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 1 0 0 0 1 1 1 1
 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0
 0 1 1 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 1 1 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1 0 1 0 1 1 0 1 1
 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 0
 0 1 0 0 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0
 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0
 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1
 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0
 0 1 0 0 1 1 0 0 0 0 0 1 

In [5]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3,random_state=23)

In [6]:
X_train.shape

(700, 5)

In [7]:
X_test.shape

(300, 5)

In [8]:
model=LogisticRegression()

In [9]:
training=model.fit(X_train,Y_train)

In [10]:
#accuracy of the model before predicting 
model.score(X_train,Y_train)

0.9457142857142857

In [11]:
y_predicted=model.predict(X_test)

In [12]:
y_predicted

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [13]:
# accuracy of the model after predicting 
accuracy_score(Y_test,y_predicted)

0.96

In [14]:
#performanace matrix of overall model
confusion_matrix(Y_test,y_predicted)

array([[146,   6],
       [  6, 142]], dtype=int64)

In [ ]:
""" overfitted model :the train accuarcy is good and test accuarcy is bad """
""" underfitted model :both the train  and test accuarcy is bad """

In [ ]:
#here are two datasets

In [ ]:
#https://archive.ics.uci.edu/datasets?search=census+income
#https://archive.ics.uci.edu/datasets?search=Energy%20efficiency    

In [ ]:
1.do end to end EDA
2.perform feature engineering and preprocessing 
3.model creation with logistic regression and perform hyperparameter
4.evalute the model and print the all score and check with auc ,roc score as well
5.give which matrix is correct according to  problem statement 