In [1]:
import pandas as  pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression , LogisticRegression
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
# from sklearn.preprocessing import OneHotEnconder , OrdinalEncoder  
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day29-sklearn-pipelines/train.csv")

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df=df.drop(columns=["PassengerId","Name","Ticket","Cabin"])

In [9]:
df.head(3)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

In [49]:
X_train,X_test, Y_train, y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.25, random_state=24)

In [52]:
X_train.head(2)

Pclass   Sex   Age  SibSp  Parch    Fare Embarked
719       3  male  33.0      0      0   7.775        S
265       2  male  36.0      0      0  10.500        S

In [53]:
Y_train.head(2)

719    0
265    0
Name: Survived, dtype: int64

In [54]:
X_test.shape

(223, 7)

In [14]:
from sklearn.preprocessing import StandardScaler 

In [15]:
std=StandardScaler()

In [55]:
df["Age"].isnull().sum()

177

In [56]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [57]:
df["Embarked"].isnull().sum()

2

In [19]:
from sklearn.compose import ColumnTransformer

In [58]:
#applying imputation
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy="most_frequent")

x_train_age=si_age.fit_transform(X_train[['Age']])
x_trained_embarked=si_embarked.fit_transform(X_train[["Embarked"]])


x_test_age=si_age.transform(X_test[['Age']])
x_test_embarked=si_embarked.transform(X_test[["Embarked"]])

In [59]:
x_trained_embarked.shape

(668, 1)

In [60]:
# one hot encoding on sex and embarked 
ohe_sex=OneHotEncoder(sparse=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse=False,handle_unknown='ignore')
X_train_sex=ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked=ohe_embarked.fit_transform(x_trained_embarked)
X_test_sex=ohe_sex.transform(X_test[['Sex']])
X_test_embarked=ohe_embarked.transform(x_test_embarked)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [61]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [62]:
X_train.head(331)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
719       3    male  33.0      0      0   7.7750        S
265       2    male  36.0      0      0  10.5000        S
686       3    male  14.0      4      1  39.6875        S
869       3    male   4.0      1      1  11.1333        S
126       3    male   NaN      0      0   7.7500        Q
..      ...     ...   ...    ...    ...      ...      ...
782       1    male  29.0      0      0  30.0000        S
51        3    male  21.0      0      0   7.8000        S
729       3  female  25.0      1      0   7.9250        S
886       2    male  27.0      0      0  13.0000        S
580       2  female  25.0      1      1  30.0000        S

[331 rows x 7 columns]

In [36]:
X_train_rem=X_train.drop(columns=['Sex','Age','Embarked'])

In [63]:
X_train_rem

Pclass  SibSp  Parch     Fare
295       1      0      0  27.7208
146       3      0      0   7.7958
281       3      0      0   7.8542
89        3      0      0   8.0500
607       1      0      0  30.5000
..      ...    ...    ...      ...
56        2      0      0  10.5000
501       3      0      0   7.7500
638       3      0      5  39.6875
348       3      1      1  15.9000
382       3      0      0   7.9250

[668 rows x 4 columns]

In [64]:
X_test_rem=X_test.drop(columns=['Sex','Age','Embarked'])

In [65]:
X_test_rem

Pclass  SibSp  Parch     Fare
169       3      0      0  56.4958
556       1      1      0  39.6000
206       3      1      0  15.8500
71        3      5      2  46.9000
677       3      0      0   9.8417
..      ...    ...    ...      ...
819       3      3      2  27.9000
97        1      0      1  63.3583
255       3      0      2  15.2458
355       3      0      0   9.5000
128       3      1      1  22.3583

[223 rows x 4 columns]

In [73]:
X_train_transformed=np.concatenate((X_train_rem,x_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed=np.concatenate((X_test_rem,x_test_age,X_test_sex,X_test_embarked),axis=1)

In [74]:
train_data=pd.DataFrame(X_train_transformed)

In [75]:
train_data

0    1    2        3          4    5    6    7    8    9
0    1.0  0.0  0.0  27.7208  33.000000  0.0  1.0  0.0  0.0  1.0
1    3.0  0.0  0.0   7.7958  36.000000  0.0  1.0  0.0  0.0  1.0
2    3.0  0.0  0.0   7.8542  14.000000  0.0  1.0  0.0  0.0  1.0
3    3.0  0.0  0.0   8.0500   4.000000  0.0  1.0  0.0  0.0  1.0
4    1.0  0.0  0.0  30.5000  29.392118  0.0  1.0  0.0  1.0  0.0
..   ...  ...  ...      ...        ...  ...  ...  ...  ...  ...
663  2.0  0.0  0.0  10.5000  19.000000  0.0  1.0  0.0  0.0  1.0
664  3.0  0.0  0.0   7.7500  26.000000  0.0  1.0  0.0  0.0  1.0
665  3.0  0.0  5.0  39.6875  25.000000  0.0  1.0  0.0  0.0  1.0
666  3.0  1.0  1.0  15.9000  19.000000  1.0  0.0  0.0  0.0  1.0
667  3.0  0.0  0.0   7.9250  30.000000  0.0  1.0  0.0  0.0  1.0

[668 rows x 10 columns]

In [76]:
clf=DecisionTreeClassifier()

In [77]:
clf

DecisionTreeClassifier()

In [78]:
clf.fit(X_train_transformed,Y_train)

DecisionTreeClassifier()

In [87]:
y_pred=clf.predict(X_test_transformed)

In [84]:

from sklearn.metrics import accuracy_score

In [88]:
accuracy_score(y_pred,y_test)

0.7174887892376681

In [89]:
import pickle

In [91]:
pickle.dump(ohe_sex,open('ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open("ohe_embarked.pkl",'wb'))
pickle.dump(clf,open('clf.pkl','wb'))

In [56]:
transformer =ColumnTransformer(transformers=[
    ("tr1",SimpleImputer(),["Age"]),
    ('tr2',SimpleImputer(strategy='most_frequent'),['Embarked']),
    ("tr3",OneHotEncoder(categories=[["male","female"]]),['Sex']),
    ("tr4",OrdinalEncoder(categories=[['S', 'C', 'Q']]),["Embarked"])
    
],remainder="passthrough")

In [92]:
# load the save model 

In [93]:
import pickle
import numpy as np


In [96]:
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('ohe_embarked.pkl','rb'))
clf=pickle.load(open('clf.pkl','rb'))


In [97]:
# user input
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [98]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [99]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [100]:
test_input_sex

array([[0., 1.]])

In [101]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [102]:
test_input_embarked

array([[0., 0., 1.]])

In [103]:
test_input_age=test_input[:,2].reshape(1,1)

In [104]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [105]:
test_input_transformed.shape

(1, 10)

In [107]:
clf.predict(test_input_transformed)

array([0], dtype=int64)