In [1]:
import torch

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
!nvidia-SMI

/bin/bash: line 1: nvidia-SMI: command not found


In [4]:
t1=torch.tensor(1.0) # there should be float number for tensor

In [5]:
t1.dtype

torch.float32

In [6]:
type(t1)

torch.Tensor

In [7]:
num=1
print(type(num))

<class 'int'>


In [8]:
# vector
v1=torch.tensor([1.,2,3])
print(type(v1))

<class 'torch.Tensor'>


In [9]:
print(v1.dtype)

torch.float32


In [10]:
print(v1)

tensor([1., 2., 3.])


In [11]:
# matrix
mt=torch.tensor([[1,2,3],[1,2,3]])
print(type(mt))
print(mt)

<class 'torch.Tensor'>
tensor([[1, 2, 3],
        [1, 2, 3]])


In [12]:
# 3d matrix
mt3=torch.tensor([
    [[1,2,3],[3,4,5],[2,4,5]],
    [[1,2,3],[34,5,6],[2,3,4]],
    [[1,2,4],[4,5,6],[2,3,4]],[[2,3,54],[2,3,4],[3,4,5]]
])

In [13]:
mt3

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 2,  4,  5]],

        [[ 1,  2,  3],
         [34,  5,  6],
         [ 2,  3,  4]],

        [[ 1,  2,  4],
         [ 4,  5,  6],
         [ 2,  3,  4]],

        [[ 2,  3, 54],
         [ 2,  3,  4],
         [ 3,  4,  5]]])

In [14]:
mt3.shape

torch.Size([4, 3, 3])

In [15]:
# tensor function

# tensor function

In [16]:
t5=torch.full((2,3,4),.3)

In [17]:
t4=torch.full((2,3,4),3)

In [18]:
t6=torch.cat((t5,t4))

In [19]:
t7=torch.sin(t6)

In [20]:
# interoperability with numpy

In [21]:
import numpy as np
x=np.array([1,2,3])
type(x)

numpy.ndarray

In [22]:
x.ndim

1

In [23]:
print(x)

[1 2 3]


In [24]:
y=torch.from_numpy(x)

In [25]:
print(y)

tensor([1, 2, 3])


In [26]:
#neural network using pytorch

#neural network using pytorch

In [104]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import  datasets
from torchvision.transforms import ToTensor,Compose, Lambda
import matplotlib.pyplot as plt



In [105]:
training_data=datasets.FashionMNIST(
    root="data" ,
    train=True,
    download=True  ,
    transform=ToTensor() ) # this function is used to generate the training data



# to generate the testing data
test_data=datasets.FashionMNIST(
    root ="data",
    train=False,
    download=True,
    transform=ToTensor()
)



In [106]:
batch_size=45
traind_data=DataLoader(training_data,batch_size=batch_size)
test_data_load=DataLoader(test_data,batch_size=batch_size)     # split the data set as the batch size


In [107]:
traind_data # call the object

In [108]:
for X , y in traind_data:
  print(X.shape)
  print(y.shape)
  break


torch.Size([45, 1, 28, 28])
torch.Size([45])


In [109]:
for X,y in test_data:
  print(X)
  break

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [110]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [111]:
# defining the model
class  NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork,self).__init__()
    self.flatten=nn.Flatten()
    self.linear_relu_stack=nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Linear(512,10)

    )
  def forward(self,x): # here i am flatten the x and then passed to the linear_relu model and
    x=self.flatten(x)
    logit=self.linear_relu_stack(x)
    return logit




In [112]:
model=NeuralNetwork().to(device) # here created the object of the Neural network
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [113]:
loss_fun=nn.CrossEntropyLoss() # defining the crossentropy and loss
optimizer=torch.optim.SGD(model.parameters(),lr=1e-3) #  defining the optimizer




In [114]:
def train(dataloader,loss_fun,optimizer,model):
  size=len(dataloader.dataset)
  model.train()
  for batch, (X,y) in enumerate (dataloader): # batch represent the index which pack the value of x and y
    X,y=X.to(device),y.to(device)
    # computed the prediction error
    yprd=model(X)
    loss=loss_fun(yprd,y)

    #backpropagetion
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [115]:
def test(dataloader,model ,loss):
  size =len(dataloader.dataset)
  num_batch=len(dataloader)
  model.eval()
  test_loss ,correct =0,0
  with torch.no_grad():
    for X ,y in dataloader:
      X,y=X.to(device),y.to(device)
      yprd=model(X)
      test_loss+=loss_fun(yprd,y).item()
      correct+=(yprd.argmax(1)==y).type(torch.float).sum().item()
  test_loss/=num_batch
  correct/=size

  print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")







In [116]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(traind_data, loss_fun,optimizer,model)
    test(test_data_load, model, loss_fun)
print("Done!")

Epoch 1
-------------------------------
loss: 2.302078  [    0/60000]
loss: 2.264027  [ 4500/60000]
loss: 2.267214  [ 9000/60000]
loss: 2.248106  [13500/60000]
loss: 2.238715  [18000/60000]
loss: 2.239968  [22500/60000]
loss: 2.197647  [27000/60000]
loss: 2.166846  [31500/60000]
loss: 2.133568  [36000/60000]
loss: 2.158457  [40500/60000]
loss: 2.107517  [45000/60000]
loss: 2.100482  [49500/60000]
loss: 2.072689  [54000/60000]
loss: 2.075609  [58500/60000]
Test Error: 
 Accuracy: 59.0%, Avg loss: 2.039978 

Epoch 2
-------------------------------
loss: 2.044739  [    0/60000]
loss: 1.982042  [ 4500/60000]
loss: 1.962214  [ 9000/60000]
loss: 1.949828  [13500/60000]
loss: 1.931093  [18000/60000]
loss: 1.937629  [22500/60000]
loss: 1.814885  [27000/60000]
loss: 1.762607  [31500/60000]
loss: 1.625408  [36000/60000]
loss: 1.766714  [40500/60000]
loss: 1.600705  [45000/60000]
loss: 1.630970  [49500/60000]
loss: 1.597082  [54000/60000]
loss: 1.565641  [58500/60000]
Test Error: 
 Accuracy: 61.4

In [117]:
#save model
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth


In [118]:
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth")) #load the saved the model

<All keys matched successfully>

In [119]:
## Prediction

classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]


model.eval()


NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [124]:
classes[7]

'Sneaker'

In [121]:
x,y = test_data[0][0], test_data[0][1]

In [122]:
with torch.no_grad():
    yprd = model(x)
    predicted, actual = classes[yprd[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"
